### ISSUE TITLE
Can you provide a babel plugin to handle wrapping?

### ISSUE THREAD

**Issue by RobinQu** [danielstjules/async-class#1]

**Comment by danielstjules** [comment]
Would that be useful? From the description:

> A solution to using promises and coroutines with classes without the overhead of babel, or the need to adopt unimplemented syntax and features, until v8/node supports ES7 async/await.

If you're using babel, why not just use async/await with your classes instead?

**Comment by RobinQu** [comment]
The initial trouble is https://github.com/babel/babel/issues/2415

async-function in babel requries es6.classes. However, es6 class is not a syntax sugar in terms of subclassing native types like Array, Map, and Set. So desugaring a class constructor to plain function declaration just won't work and is totally useless if you are using node 4.0.0+.

This repo is the closest thing I can find to solve my problem.

However, I am using babel's other es7 transformers. I really want a plugin to replace bable's `es7.asyncFunctions` transformer.

I think a plugin is useful indeed.  
1. People can get async function support with code down-graded to es6 not es5. 
2. Explicit calls of `wrapX` is no longer needed, because babel can find async function declarations and add `wrapX` calls for those async functions.

**Comment by danielstjules** [comment]
Interesting idea - sounds like something worth exploring. However, async-class requires more than just ES6 syntax/features. Bluebird.coroutine, for example, is not something provided by the native promise API..

**Comment by danielstjules** [comment]
Assuming this is no longer an issue, and I don't personally use babel for server side code.
