### ISSUE TITLE
Remove bluebird?

### ISSUE THREAD

**Issue by jimmywarting** [danielstjules/async-class#3]
Is it really necessary to include the hole bluebird library for a simple coroutine?

There is many smaller co libraries [[1](https://www.npmjs.com/package/co6)][[2](https://www.npmjs.com/package/co)] out there that dose the job well, I believe you could write a own also

**Comment by danielstjules** [comment]
I've never used `co6`, but the stack traces generated by `co` aren't always great. I'd much rather use bluebird for that reason, sorry.

**Comment by overlookmotel** [comment]
@danielstjules I'm broadly with you. But then I'm only using this stuff server-side with Node so additional dependencies don't bother me.

I guess if you're deploying to the browser, and if you're choosing to use another wrapper based on native promises, then the extra weight of bluebird is a pointless burden.

**Comment by danielstjules** [comment]
The original issue was about removing bluebird in favor of another library, which I disagreed with - bluebird coroutines tend to offer the best dev experience. However, giving the user the option to use whichever wrapper they'd like is a fantastic alternative. :)

**Comment by jimmywarting** [comment]
My intention with this issue was more to reduce the dependencies.
co-wrap and bluebird coroutines is basically same same - so it doesn't bother me so much which one i use

**Comment by danielstjules** [comment]
Sounds good to me! And removing bluebird as a dependency can be done in a minor release, since semver only defines the public API as of 1.0.0

**Comment by danielstjules** [comment]
Looks like there's a fork :)
https://github.com/viniciusps2/async-class-co

**Comment by jimmywarting** [comment]
don't need it anymore can run async await in node already !
