### ISSUE TITLE
Option to provide alternative wrapper

### ISSUE THREAD

**Issue by overlookmotel** [danielstjules/async-class#4]
Hi.

[Sequelize](https://www.npmjs.com/package/sequelize) is switching over to ES6 classes and coroutines and your module looks like the perfect solution to defining classes with async methods in a nice clean way.

However, I wondered if you'd consider adding an option to provide an alternative wrapper to `bluebird.coroutine`?

Various use cases I can think of:
1. Using custom yield handlers (e.g. to get `co`-like support for yielding arrays of promises)
2. User wants wrapped functions to return bluebird v3 promises rather than v2
3. User wants to use a version of bluebird that's shimmed to support [CLS](https://www.npmjs.com/package/continuation-local-storage)

There'd be various ways to implement this:
##### 1A. Simple extra optional argument

``` js
// API: wrap( klass [, methodNames] [, wrapper] )
wrap( klass, ['myMethod'], co.wrap );
wrap( klass, co.wrap );
```
##### 1B. Options object

``` js
// API: wrap( klass [, methodNames | wrapper | options] )
wrap( klass, ['myMethod'] ); // methodNames provided, no wrapper provided
wrap( klass, co.wrap ); // wrapper provided, no methodNames
wrap( klass, { methodNames: ['myMethod'], wrapper: co.wrap } ); // both
```
##### 1C. Overloaded arguments

``` js
// API: wrap( klass, [, methodNames] [, wrapper] [, options] )
// all of these legal usage:
wrap( klass );
wrap( klass, ['myMethod'] );
wrap( klass, co.wrap );
wrap( klass, { wrapper: co.wrap } );
wrap( klass, ['myMethod'], { wrapper: co.wrap } );
wrap( klass, co.wrap, { methodNames: ['myMethod'] } );
```

Arguments could be provided in any order and which arg is which inferred by the type. i.e. Array is `methodNames`, Object is `options`, Function is `wrapper`.

Personally I favor this approach as it allows maximum flexibility and the `options` object allows room for expansion if you want to add other options in future.

NB Would be back-compatible with current syntax.
#### 2. Property on `asyncClass`

``` js
var asyncClass = require('async-class');
asyncClass.wrapper = require('co').wrap;

class FakeDataStore {
    /* ... */
}

module.exports = asyncClass.wrap( FakeDataStore );
```

Personally, I'm not keen on this kind of interface, as it changes the "global" instance of `async-class`. i.e. if another module somewhere else in the app uses `require('async-class')`, it may get the mutated version, causing it to malfunction.

Another approach could be to define a method `asyncClass.useWrapper( wrapper )` which returns a _new_ instance of `async-class` using that wrapper, and doesn't mutate the "global" version.

``` js
var asyncClass = require('async-class').useWrapper( require('co').wrap );
```

The latter is the kind of pattern I used in [co-use](https://www.npmjs.com/package/co-use) and it seems to work well.
#### Conclusion

This feature would be really helpful to me and I'd be really happy to work up a PR for it, if you're willing.

Please let me know if you'd accept that and, if so, what API you prefer.

**Comment by danielstjules** [comment]
Sounds good! :) I think I'd offer an API that featured both 1A and 2 as an option. Option 2 essentially saves the user from having to wrap it themselves for convenience with something resembling:

``` javascript
let asyncClass = require('async-class');
let co = require('co');

module.exports = function(klass, options) {
  options.wrapper = co.wrap;
  return asyncClass.wrap(klass, options);
};
```

It's not a lot of code, but more convenient to not have to do it :)

**Comment by overlookmotel** [comment]
I've implemented the `wrapper` option (see PR #5). So that's part 1 done.

For the 2nd part of the interface, do you go with my suggestion of `.useOptions()`? (or I suppose it could be called just `.options()`)

**Comment by jimmywarting** [comment]
Should probably also make bluebird as an optional dependencies instead?
Would be unnecessary to have both

**Comment by danielstjules** [comment]
`.options()` is fine :) And if you find yourself busy, I can takeover the branch whenever. Thanks!

**Comment by overlookmotel** [comment]
@jimmywarting Well that'd break backwards compatibility so would have to be a semver major release. @danielstjules Would it be OK with you to remove the `bluebird` dependency and it'd be up to the user to make sure it's in their `package.json`? Or do you prefer to keep it as is? I'm easy either way.

**Comment by danielstjules** [comment]
I'd rather keep bluebird for now, and consider removing it in a subsequent major, tracking any changes in a different issue/PR: https://github.com/danielstjules/async-class/issues/3 I find it it less enticing to offer a module that doesn't actually work out of the box.

**Comment by overlookmotel** [comment]
Hi @danielstjules.

I've made a bit of progress on PR #5. I ended up adding 3 options:

`options.wrapper` is wrapper to use for generators (defaults to `Bluebird.coroutine`)
`options.asyncWrapper` is wrapper to use for async methods (defaults to `Bluebird.method`)
`options.asyncWrapCondition` is function to determine whether to apply `asyncWrapper` or not

Default value of `options.asyncWrapCondition` is `function(key) { return key.endsWith('Async'); }` i.e. same behavior as before. Purpose is to allow user to customise when wrapper is applied - some people use other conventions than "method name ends with 'Async'".

`asyncWrapCondition` is called with arguments `(key, target, isStatic)` (`isStatic == true` if it's a static method, `false` if prototype method). I think with these, it gives user all info needed to construct any condition algorithm they might desire.

`methodNames` (or `options.methodNames`) works as before.

I guess `options.wrapCondition` could also be added to API to allow user to prevent some generator functions being wrapped - but I haven't implemented that.

What do you think?

I've been very tied up with work, so haven't written any tests or got on to implementing `.options()`. But I think this would be a good point to get your feedback.

**Comment by overlookmotel** [comment]
Ping @danielstjules

**Comment by danielstjules** [comment]
Closing via https://github.com/danielstjules/async-class/pull/5#issuecomment-283753157
Thanks again though! :)
