### ISSUE TITLE
Does this module cause any problems for debuggers?

### ISSUE THREAD

**Issue by greaber** [danielstjules/async-class#6]
Hi, I am thinking about using this module and I was wondering if there are any gotchas or downsides to using this technique.  My coding partner, who comes from a C# background, thought patching classes dynamically sounded hacky, and I would like to reassure him and myself.  The one concrete possible problem that I have thought of and am uncertain about is whether using the module could interact badly with using debuggers, like Webstorm's debugger or node-inspector.

**Comment by danielstjules** [comment]
Haven't noticed any issues :) It's not any different from using co/bluebird.coroutine to wrap functions/methods. If you're familiar with the verbosity of promise stack traces, then this should feel pretty similar.

**Comment by greaber** [comment]
Feel free to leave this closed.  I am not actively involved with node programming at the moment.  But the issue I was worried about wasn't stack traces but breakpoints.  I never ended up actually testing to see if there were any issues unfortunately.
